[colors]
[colors.primary]
background = "#07070B"
foreground = "#f0dbcf"

[colors.normal]
black   = "#07070B"
red     = "#DD5C5C"
green   = "#9CAB8D"
yellow  = "#b4b691"
blue    = "#9a9dbc"
magenta = "#c09dc8"
cyan    = "#abc8c9"
white   = "#D7A88D"

[colors.bright]
black   = "#353543"
red     = "#f0a5a5"
green   = "#cad3c1"
yellow  = "#dadcc7"
blue    = "#d0d2e1"
magenta = "#e6d7ea"
cyan    = "#e2eded"
white   = "#f0dbcf"

[colors.cursor]
text   = "#07070B"
cursor = "#f0dbcf"
