# Background and foreground colors
background = #07070B
foreground = #f0dbcf

# Standard colors
palette = 0=#07070B
palette = 1=#DD5C5C
palette = 2=#9CAB8D
palette = 3=#b4b691
palette = 4=#9a9dbc
palette = 5=#c09dc8
palette = 6=#abc8c9
palette = 7=#D7A88D

# Bright colors
palette = 8=#353543
palette = 9=#f0a5a5
palette = 10=#cad3c1
palette = 11=#dadcc7
palette = 12=#d0d2e1
palette = 13=#e6d7ea
palette = 14=#e2eded
palette = 15=#f0dbcf
