$color = rgba(7, 7, 11, 1)
$inner_color = rgba(7, 7, 11, 0.66)
$outer_color = rgba(192, 157, 200, 1)
$font_color = rgba(240, 219, 207, 1)
$placeholder_color = rgba(240, 219, 207, 0.7)
$check_color = rgba(171, 200, 201, 1)
