background            #07070B
foreground            #f0dbcf

# black
color0  #07070B
color8  #353543

# red
color1  #DD5C5C
color9  #f0a5a5

# green
color2  #9CAB8D
color10 #cad3c1

# yellow
color3  #b4b691
color11 #dadcc7

# blue
color4  #9a9dbc
color12 #d0d2e1

# magenta
color5  #c09dc8
color13 #e6d7ea

#cyan
color6  #abc8c9
color14 #e2eded

#white
color7  #D7A88D
color15 #f0dbcf


