general {
    lock_cmd = omarchy-lock-screen                         # lock screen and 1password
    before_sleep_cmd = loginctl lock-session               # lock before suspend.
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on  # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                      # wait until screen is locked
}

# 1. Turn off keyboard backlight (14 min)
listener {
    timeout = 840
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0
    on-resume = brightnessctl -rd '*::kbd_backlight'
}

# 2. Start screensaver (15 min)
listener {
    timeout = 900
    on-timeout = pidof hyprlock || omarchy-launch-screensaver
}

# 3. Lock screen (16 min)
listener {
    timeout = 960
    on-timeout = loginctl lock-session
}

# 4. Turn off display (16.5 min, after lock has engaged)
listener {
    timeout = 990
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}
